"Show more" button on tool view
euphorie/Euphorie pull request #420
Opened 2022-07-06 09:26 UTC by reinhardt

Tool view: "show more" button if there are existing sesions.

Refs syslabcom/scrum#445

2022-07-06 09:42 UTC, ale-rt requested changes

2022-07-06 09:42 UTC, ale-rt commented on src/euphorie/client/browser/templates/tool_sessions.pt
> +                  >Lesen Sie mehr</button>
This looks untranslated

2022-07-07 04:13 UTC, reinhardt commented
Is this good to go now?

2022-07-07 07:02 UTC, ale-rt approved these changes
LGTM

2022-07-07 07:02 UTC, merged