Text tweak “find a consultant”
euphorie/Euphorie pull request #602
Opened 2023-06-14 14:33 UTC by reinhardt

syslabcom/scrum#1285

2023-06-15 17:46 UTC, thet submitted a review, later dismissed
Two comments which need to be fixed.
Also, please rebase or otherwise fix the merge conflicts.
Other thant that, LGTM

2023-06-15 17:46 UTC, thet commented on src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
> +msgstr "Finden Sie einen OiRA-Berater, den Sie kontaktieren oder zu Ihrer Organisation hinzufügen möchten, um Unterstützung zu leisten."
Shouldn't that be:
```suggestion
msgstr "Finden Sie einen OiRA-Berater, den Sie kontaktieren oder zu Ihrer Organisation hinzufügen möchten um Unterstützung zu erhalten."
```

2023-06-15 17:46 UTC, thet commented on src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
> +msgstr "Ontdek hoe u in contact kunt komen met een OiRA-adviseur op ${email}."
I‌ think `${email}` is wrong here. The original msgstr doesn't conain a `i18n:name` part.

2023-06-15 17:50 UTC, thet requested changes
please see the comments

2023-06-16 06:08 UTC, reinhardt commented
> Two comments which need to be fixed. Also, please rebase or otherwise fix the merge conflicts. Other thant that, LGTM

Usually I don't copy translations from prototype for osha because they go through their translation process anyway. This time I thought I'd try it, but apparently it was not a good idea. I've removed them again.

2023-06-16 07:58 UTC, thet approved these changes

2023-06-16 07:58 UTC, merged