Pin a specific version of slc.pre-commit
euphorie/Euphorie pull request #638
Opened 2023-07-27 09:24 UTC by reinhardt

2023-07-27 09:29 UTC, ale-rt requested changes

2023-07-27 09:29 UTC, ale-rt commented on .pre-commit-config.yaml
> +    rev: v1.0.0
Sorry, can we please stick to consolidate version number schemes (i.e. 1.0.0)?
I have seen too much in my life to go for the version number you are proposing.

2023-07-27 11:40 UTC, reinhardt commented on .pre-commit-config.yaml
> +    rev: v1.0.0
```suggestion
    rev: 1.0.0
```

2023-07-27 11:41 UTC, reinhardt commented on .pre-commit-config.yaml
> +    rev: v1.0.0
FWIW github claims that “It’s common practice to prefix your version names with the letter v.”

2023-07-28 07:01 UTC, ale-rt approved these changes

2023-07-28 07:02 UTC, merged