More short report tweaks.
euphorie/Euphorie pull request #649
Opened 2023-10-10 11:42 UTC by reinhardt

Keep top/bottom cell borders between risks of same module.

syslabcom/scrum#1295

2023-10-10 12:24 UTC, ale-rt requested changes
`for idx in range(1) ` looks like code obfuscation to me.

Is that a leftover?

2023-10-10 12:33 UTC, ale-rt reviewed
Apparently it comes from this one https://github.com/syslabcom/daimler.oira/commit/b7d0d4642586c434adc437cc0fbae19d7f230096#diff-611f13a21a8050fbb7ed577516423f0b6fb62298c842d004a2b6c7252ce232f2R159-R161, which at least explains the reason of the strange `range(1)`.
It would be nice to have clearer code/docs.
The future developers will really be pleased.

2023-10-11 04:27 UTC, reinhardt commented
I got rid of the loop.

2023-10-11 04:29 UTC, reinhardt commented
Here's another PR to also change the original bit of code: #650

2023-10-11 06:42 UTC, ale-rt approved these changes

2023-10-11 06:42 UTC, merged