Use weasyprint for PDF generation
euphorie/Euphorie pull request #683
Opened 2023-12-21 14:18 UTC by reinhardt

syslabcom/scrum#732

2023-12-21 15:16 UTC, ale-rt requested changes
This is not building for me due to missing pins.
```
Version and requirements information containing pillow:
  [versions] constraint on pillow: 6.2.2
  Requirement of weasyprint: Pillow>=9.1.0
While:
  Installing instance.
Error: The requirement ('Pillow>=9.1.0') is not allowed by your [versions] constraint (6.2.2)
make: *** [Makefile:13: .installed.cfg] Error 1
```

Please before continuing check #603 and rebase on it.

Also take in to account the same notes I did on the other PR (logging, error loading resources and so on).

2024-01-10 11:58 UTC, ale-rt commented on versions-6.0.cfg
> +Pillow = 9.5.0
This is not needed:
```suggestion
```

Plone 6.0.9 already has the proper version set:
```
ale@avo:~/Code/plone/projects/daimlertruck$ ploneversions 6.0.9|grep Pillow
Pillow = 9.5.0
```

2024-01-10 12:00 UTC, ale-rt commented on README.rst
> +Euphorie 12 uses ``weasyprint`` to render PDF files.
This sentence should be fixed.
At least update the version number.

2024-01-12 15:47 UTC, reinhardt commented on README.rst
> +Euphorie 12 uses ``weasyprint`` to render PDF files.
```suggestion
Euphorie uses ``weasyprint`` to render PDF files.
```

2024-01-15 14:10 UTC, reinhardt commented
Is this OK to merge or do you want the log level hack from quaive/ploneintranet#5319 here as well?

2024-01-15 15:46 UTC, ale-rt commented
I was not yet able to try this branch,

The goal for me is to check that we have a solution that produces a PDF with a quality comparable with the one wkhtmltopdf was producing and that has no side effects.
I would not like to review this PR again and come back to you asking changes because the PDF differs too much from the previous implementation or because we are flooded by log lines.

So please, check that the PR is in a mergeable state before I invest time in reviewing it.

Thank you.

2024-01-15 16:00 UTC, reinhardt commented
> produces a PDF with a quality comparable with the one wkhtmltopdf was producing and that has no side effects

I'm not aware that this is part of a code review. It sounds like you want to do QA already.

2024-01-29 09:46 UTC, ale-rt commented
I tested this and the problem of the excessive logging still exists.
In addition, the two produced PDFs look quite a lot different.
![image](https://github.com/euphorie/Euphorie/assets/1300763/54b335c7-56b2-4de2-9c26-bf9309f8e0c9)
Left is wkhtmltopdf, right is weasyprint.

I would say it would be ok if they are not identical but IMO the font size is too big for the new report.
This also has the consequence of having the date split on two lines:
![image](https://github.com/euphorie/Euphorie/assets/1300763/2a7828c3-c606-40e5-ae18-e9b2cbd22343)

Can you please recheck?

2024-01-31 09:56 UTC, ale-rt approved these changes
I really don't think 8px is the way to go, sorry.
Before we had the possibility to setup options for wkhtmltopdf, and it is a pity we cannot do that anymore.
Anyway, I am merging with my eyes closed.

2024-01-31 09:56 UTC, merged