Similar titles: Store HTML as annotation until new search is triggered
euphorie/Euphorie pull request #763
Opened 2024-09-25 13:14 UTC by reinhardt

Ref syslabcom/scrum#2517

2024-09-26 06:50 UTC, ale-rt requested changes
Nice job, but this will overwrite the results for every search, which is not ideal.

Please add a third button to display the results set in the annotations (if present).
The file has to be set by a cron job nightly.

If it is unclear, let's have a call.

2024-09-26 09:17 UTC, reinhardt commented
Is this any closer to what you have in mind? https://github.com/euphorie/Euphorie/pull/763/commits/441628f3a1f3bdcecd0aa09f5008465614a4e560

2024-09-26 12:21 UTC, ale-rt commented
Yes, closer. 

This still overwrites the results for every search that a user makes.
Do not do that, please.

Also, I would like to keep the behavior we had before when clicking the search button: the results should be displayed below the form.

Thanks a lot

2024-09-26 13:43 UTC, reinhardt commented
Another try: https://github.com/euphorie/Euphorie/pull/763/commits/6823104ef88523b68971eb4f2313658e34e78a3b

The cron job will need to make a post request, or we can make a shortcut view or something that calls `similar-titles-stored` internally.

2024-09-27 06:35 UTC, ale-rt approved these changes

2024-09-30 07:46 UTC, merged